# Generated by Django 6.0.4 on 2026-04-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prf', models.IntegerField(unique=True)),
                ('data', models.DateField()),
                ('dia_semana', models.CharField(max_length=20)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('ano', models.IntegerField()),
                ('uf', models.CharField(max_length=2)),
                ('br', models.CharField(max_length=10)),
                ('km', models.CharField(max_length=10)),
                ('municipio', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('regional', models.CharField(blank=True, max_length=20)),
                ('delegacia', models.CharField(blank=True, max_length=30)),
                ('uop', models.CharField(blank=True, max_length=40)),
                ('causa_acidente', models.CharField(max_length=200)),
                ('tipo_acidente', models.CharField(max_length=100)),
                ('classificacao_acidente', models.CharField(blank=True, max_length=50)),
                ('fase_dia', models.CharField(max_length=30)),
                ('sentido_via', models.CharField(blank=True, max_length=30)),
                ('condicao_metereologica', models.CharField(blank=True, max_length=50)),
                ('tipo_pista', models.CharField(blank=True, max_length=30)),
                ('tracado_via', models.CharField(blank=True, max_length=100)),
                ('uso_solo', models.CharField(blank=True, max_length=10)),
                ('pessoas', models.IntegerField(default=0)),
                ('mortos', models.IntegerField(default=0)),
                ('feridos_leves', models.IntegerField(default=0)),
                ('feridos_graves', models.IntegerField(default=0)),
                ('ilesos', models.IntegerField(default=0)),
                ('ignorados', models.IntegerField(default=0)),
                ('feridos', models.IntegerField(default=0)),
                ('veiculos', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
